services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=products_admin
      - POSTGRES_USER=alejandroch
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=alejandroch@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80